### ISSUE TITLE
Sponge Dupes

### ISSUE THREAD

**Issue by n00bslayr94** [Catalyst-Serendipity/Sponge#1]
PM 5.11.0 - see video - sponge places but also doesnt change amount. Sponges can be mined. 

https://github.com/Catalyst-Serendipity/Sponge/assets/132199379/f22b18fc-344a-4e6a-8b38-b94bb80db6a7

**Comment by nicholass003** [comment]
Hello! Thank you for helping to identify the bug on GitHub. Your contribution is greatly appreciated! The bug has already been fixed in the latest update https://github.com/Catalyst-Serendipity/Sponge/commit/f3f4cfb88befa7a5cbf734c7417eebad4bd4bb79
