### ISSUE TITLE
Sponge now doesn't work?

### ISSUE THREAD

**Issue by n00bslayr94** [Catalyst-Serendipity/Sponge#2]
Hi - thanks so much for taking a look at my last report. I added the latest version to my server and while it doesnt dupe the sponge anymore, it also doesn't soak up water?

https://github.com/Catalyst-Serendipity/Sponge/assets/132199379/2f6399f9-9727-4d74-b6dc-c1bc5d284b49

**Comment by nicholass003** [comment]
> Hi - thanks so much for taking a look at my last report. I added the latest version to my server and while it doesnt dupe the sponge anymore, it also doesn't soak up water?
> 
>  Untitled.video.34.mp4

Hello @n00bslayr94 ! Thank you for creating the issue again! I have tested this on my server, and it works fine. Please try restarting the server or updating PMMP to the latest version. Thank you!

https://github.com/Catalyst-Serendipity/Sponge/assets/142091702/b9a93bbf-6781-47c3-b088-e6955495118a

https://github.com/Catalyst-Serendipity/Sponge/assets/142091702/82dc6b64-af71-4256-8c49-a67750ad33fa
